version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_storage:/usr/share/elasticsearch/data
    restart: always

<<<<<<< HEAD
volumes:
  qdrant_storage:
  elasticsearch_storage:
    driver: local
    driver_opts:
      type: none
      device: D:/ElasticSearch_Data
      o: bind
=======
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document_store
      MYSQL_USER: tiendoan
      MYSQL_PASSWORD: tiendoan
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  qdrant_storage:
  mysql_data:
>>>>>>> 949eb90fc113c2f81610069fc66bbb434a346ecc
